<a href="https://colab.research.google.com/github/pavani2406/Pythonpractice-9-11-2024/blob/main/pythonparctice_11_9_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating a class:

In [12]:
class employee:
  c_name = 'abc'
  def __init__(self,name,age,salary):
    self.name = name
    self.age = age
    self.salary = salary

  # Indent the show function to make it a method of the employee class
  def show(self):
    print("Employee details: ", self.name, self.age, self.salary)

emp1 = employee("Harry", 21, 12000)
emp1.show()

Employee details:  Harry 21 12000


In [13]:
emp2 = employee("pavani", 20, 45000)
emp2.show()

Employee details:  pavani 20 45000


encap

In [15]:
class Employee:
  def __init__(self, name, salary):
    self.name = name
    self.__salary = salary
  def show(self):
    print("Name is ", self.name, "and salary is", self.__salary)


polymorphisim

In [40]:
class circle:
  pi = 3.14159
  def __init__(self,radius) :
    self.radius = radius

  def calculate_area(self): # This method needs to be defined within the class
    print("area of circle: ",self.pi*self.radius*self.radius)

class Rectangle:
  def __init__(self, length, width):
    self.length = length
    self.width = width

  def calculate_area(self):
    print("area of rectangle: ", self.length * self.width)

def area(shape):
  shape.calculate_area()

cir = circle(5)
rect = Rectangle(11,5)

area(cir)
area(rect)

area of circle:  78.53975
area of rectangle:  55


Inheritance

In [42]:
class vehicle:
  def __init__(self,name,color,price):
    self.name = name
    self.color = color
    self.price = price

  def info(self):
    print("vehicle details: ", self.name, self.color, self.price)


class car(vehicle):
  def change_gear(self,no):
    print(self.name,'chang gear to numer, no')


car = car('tata','white',10000000)
car.info()
car.change_gear(10)

vehicle details:  tata white 10000000
tata chang gear to numer, no


#numpy

In [45]:
import numpy as np
a = np.random.randint(1,10,8)
print(a)

[7 2 5 7 2 3 7 8]


In [46]:
b=np.random.randint(10,30,6)
print(b)

[12 24 22 28 25 21]


In [47]:
c=np.random.random((10,5))
print(c)

#first 5 rows
new = c[:5]
print("first 5 roess new array = ", new)

[[0.80919332 0.43920782 0.91572565 0.20878385 0.29212743]
 [0.58475606 0.53409296 0.45866701 0.23364779 0.61122946]
 [0.08182295 0.86806445 0.68964582 0.32935223 0.49290607]
 [0.54970462 0.2926718  0.77543793 0.5648267  0.91113338]
 [0.55776388 0.93463058 0.31302654 0.20691584 0.09363064]
 [0.16855384 0.52742618 0.67153376 0.15196634 0.60281309]
 [0.64287137 0.57078665 0.16324085 0.45136572 0.5967532 ]
 [0.46867382 0.23678749 0.0818177  0.05850295 0.37080136]
 [0.03570184 0.95464634 0.1424216  0.33390631 0.00546498]
 [0.21920037 0.52120203 0.83072848 0.14296931 0.07372098]]
first 5 roess new array =  [[0.80919332 0.43920782 0.91572565 0.20878385 0.29212743]
 [0.58475606 0.53409296 0.45866701 0.23364779 0.61122946]
 [0.08182295 0.86806445 0.68964582 0.32935223 0.49290607]
 [0.54970462 0.2926718  0.77543793 0.5648267  0.91113338]
 [0.55776388 0.93463058 0.31302654 0.20691584 0.09363064]]


In [50]:
#random numbers with integer numbers
x=np.random.randint((5,5))
print(x)

max,min=x.max(),x.min()
print("highesr = ", max)
print("lowest = ", min)

[0 2]
highesr =  2
lowest =  0


In [51]:
#with random numbers
x=np.random.random((5,5))
print(x)

max,min=x.max(),x.min()
print("highesr = ", max)
print("lowest = ", min)

[[0.99265934 0.2968493  0.33639228 0.9163132  0.2349515 ]
 [0.75738595 0.60259725 0.31073601 0.28953654 0.24901411]
 [0.52995213 0.52554575 0.26964978 0.3108047  0.84124111]
 [0.75890398 0.29901022 0.42136458 0.65257762 0.82609927]
 [0.82900357 0.53187163 0.2167642  0.06918411 0.71304003]]
highesr =  0.992659340647189
lowest =  0.06918411093135357


In [55]:
z=np.arange(2,12)
print(z)
np.random.shuffle(z)
print(z)

[ 2  3  4  5  6  7  8  9 10 11]
[ 6  9 11  2 10  3  7  8  4  5]


In [56]:
import numpy as np

y=np.random.randint(0,10,40)
print(y)

#most frequent and least frq values
print("most freq values are : ", np.bincount(y).argmax())
print("least freq values are : ", np.bincount(y).argmin())

[8 8 7 9 1 5 0 6 3 9 5 8 5 2 9 0 6 0 9 4 5 8 7 6 8 6 8 4 1 8 7 6 9 8 8 4 0
 9 3 0]
most freq values are :  8
least freq values are :  2


In [59]:
import numpy as np
n=int(input("enter the num of characters: "))
l=[]

for i in range(n):
  c=input("enter a character")
  l.append(c)

n = np.array(l)
print(type(n))

vowels=['a','e','i','o','u','A','E','I','O','U']
cv=0
cu=0
cl=0

for c in n:
  if c in vowels:
    cv = cv+1
  if c.islower():
    cl = cl+1
  if c.isupper():
    cu=cu+1

print(cv,cu,cl)

enter the num of characters: 3
enter a charactera
enter a charactere
enter a characteri
<class 'numpy.ndarray'>
3 0 3
